# Generated by Django 2.0.2 on 2018-05-01 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='publishe',
            new_name='published',
        ),
    ]
